# Key bindings for taking screenshots
#
# The image files will be written to XDG_SCREENSHOTS_DIR if this is set
# or defined in user-dirs.dir, or to a fallback location XDG_PICTURES_DIR.
#
# Copy the file to ~/.config/sway/config.d/60-bindings-screenshot.conf (or to
# your $XDG_CONFIG_HOME location if set differently) to be able to overwrite
# existing shortcuts.
# Check 'man grimshot' for additional commands that you may find useful.
#
# Requires:     grimshot

bindsym {
    # Copy to Clipboard
    # Copy the currently active output
    Print       exec grimshot copy output
    # Copy the currently active window
    Ctrl+Print   exec grimshot copy active
    # Select and copy a custom rectangular area
    Shift+Print  exec grimshot copy area

    # Save Screenshot
    # Capture the currently active output
    Alt+Print       exec grimshot copy output
    # Capture the currently active window
    Ctrl+Alt+Print   exec grimshot copy active
    # Select and capture a custom rectangular area
    Shift+Alt+Print  exec grimshot copy area
}

